# docker-compose configuration for local development
#
# docker-compose run cli composer install --prefer-dist

# API STACK
# =========

# Includes a container to run commands locally - a Dockerized shell
cli:
  image: schmunk42/php:5.6-cli-yii-2.0.3-app-basic
  volumes:
   - .:/app
  links:
   - web:WEB
  working_dir: /app
  #links:
  #  - db

# The php-fpm server for interpreting php code
fpm:
  image: schmunk42/php:5.6-fpm-yii-2.0.3-runtime
  #  - db
  volumes:
   - .:/app
  environment:
    YII_DEBUG: 1
    YII_ENV: dev

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php-fpm server
web:
  image: schmunk42/nginx:1.7
  links:
    - fpm:PHPFPM
  volumes:
   - .:/app
  ports:
    - "80"
  environment:
    VIRTUAL_HOST: ~^dev\.yii2\..*
    NGINX_ERROR_LOG_LEVEL: 'notice'

db:
    image: mariadb
    ports:
        - "3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: secretroot
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev123
        MYSQL_DATABASE: dev-yii2