# Docker compose configuration for local development

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php-fpm server
nginx:
  image: nginx:1.7
  links:
    - phpfpm
    - memcached
  volumes:
   - .:/app
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# The php-fpm server for interpreting php code
phpfpm:
  image: php:5.6-fpm
  links:
    - memcached
  volumes:
   - .:/app
  ports:
   - "9000"
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

# Memcached server for serving cached contents via the nginx-memcache plugin
memcached:
  image: memcached:1.4.22
  ports:
    - "11211"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  ports:
    - "25"
    - "1080"

# A container to run commands locally - a Dockerized shell
shell:
  image: phundament/app:development
  volumes:
   - .:/app
  working_dir: '/app'
  command: "true"

# A container that is linked to and thus can output linked information about running containers
info:
  image: phundament/app:development
  links:
    - nginx
    - phpfpm
    - memcached
  volumes:
   - .:/app
  working_dir: '/app'
  command: "true"

# Selenium...

# Includes a cmd to run commands defined by env vars so that administration tasks can be run by redeploying the container
#tutumworker:
#  image: debian:jessie
#  volumes:
#   - .:/app
#  environment:
#    APP_DIR: '/app'
#    WORKER_CMD: '/bin/bash echo "Hello"'
#  command: "/app/worker/run.sh"

