# Data only container that includes project source code at /app and generates
# some configuration files generated based on env vars and composer.json.
# /app is subsequently used as document root in php-fpm and nginx config

project:
  image: gapminder/cms:feature_dockerfile-based-build-cms-clean-db
  volumes:
   - /app
  environment:
    FOO: bar

# Includes a cmd to run commands defined by env vars so that administration tasks can be run by redeploying the container
worker:
  image: php:5.6-cli
  volumes_from:
    - project
  environment:
    WORKER_CMD: '/bin/bash echo "Hello"'
  command: ["/bin/bash", "/app/server-config/generate.sh", "&&", "/app/server-config/run-worker-cmd.sh"]

# The php-fpm server for interpreting php code
phpfpm:
  image: php:5.6-fpm
  links:
    - project
  volumes_from:
    - project
  ports:
   - "9000"
  command: ["/bin/bash", "/app/server-config/generate.sh", "&&", "php-fpm"]

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php-fpm server
nginx:
  image: nginx:1.7
  links:
    - project
    - phpfpm
    - memcached
  volumes_from:
    - project
  ports:
    - "80"
    - "443"
  command: ["/bin/bash", "/app/server-config/generate.sh", "&&", "nginx", "-g", "daemon off;"]

# Memcached server for serving cached contents via the nginx-memcache plugin
memcached:
  image: memcached:1.4.22
  ports:
    - "11211"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  ports:
    - "25"
    - "1080"
